### ISSUE TITLE
Crashes on open

### ISSUE THREAD

**Issue by gesquive** [linux-man/ezame#3]
I'm on Ubuntu 14.04.1 and whenever I tried to open ezame, I would get the following stack trace:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/dist-packages/ezame/__main__.py", line 988, in <module>
    app = Ezame()
  File "/usr/lib/python2.7/dist-packages/ezame/__main__.py", line 938, in __init__
    self.load_menu()
  File "/usr/lib/python2.7/dist-packages/ezame/__main__.py", line 785, in load_menu
    self.load_freedesktop()
  File "/usr/lib/python2.7/dist-packages/ezame/__main__.py", line 853, in load_freedesktop
    else: self.menu = parse()
  File "/usr/lib/python2.7/dist-packages/xdg/Menu.py", line 570, in parse
    raise ParsingError('File not found', "/etc/xdg/menus/%s" % candidate)
xdg.Exceptions.ParsingError: ParsingError in file '/etc/xdg/menus/debian-menu.menu', File not found
```

I was able to fix it by installing the debian package `menu-xdg` But I don't feel like this should be necessary. That file shouldn't be needed by ezame.

**Comment by linux-man** [comment]
It looks for the menu file and don't find it (bad exception handling). I really must apologise to all. I have a new version that drops most of the dependencies (and also drops python 2 compatibility), and really separate the desktop files and the menu files edition, but I didn't have the time to finish the UI.
